/*
 * Copyright 2024 ISNing
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.isning.gradle.plugins.cmake.params.entries.lang

import io.github.isning.gradle.plugins.cmake.params.entries.CMakeCacheEntriesWithValueAutoGenerated

interface CEntriesProps {
    val compileFeatures: String?
}

interface CEntries : CEntriesProps, LanguageSpecifiedEntries

interface ModifiableCEntries : CEntries, ModifiableLanguageSpecifiedEntries {
    override var compileFeatures: String?
}

interface CEntriesAutoGen : CEntries, CMakeCacheEntriesWithValueAutoGenerated {
    override val propertyNameToKey: Map<String, String>
        get() = mapOf(
            "compileFeatures" to "C_COMPILE_FEATURES",
        )
}

open class CEntriesImpl : LanguageSpecifiedEntriesImpl("C"), CEntriesAutoGen {
    override val compileFeatures: String? = null

    override val propertyNameToKey: Map<String, String>
        get() = super<LanguageSpecifiedEntriesImpl>.propertyNameToKey + super<CEntriesAutoGen>.propertyNameToKey
}

class ModifiableCEntriesImpl : ModifiableLanguageSpecifiedEntriesImpl("C"), ModifiableCEntries,
    CEntriesAutoGen {
    override var compileFeatures: String? by recorder.observed(null)

    override val propertyNameToKey: Map<String, String>
        get() = super<ModifiableLanguageSpecifiedEntriesImpl>.propertyNameToKey +
                super<CEntriesAutoGen>.propertyNameToKey
}