/*
 * Copyright 2024 ISNing
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.isning.gradle.plugins.cmake.params.entries.platform

import io.github.isning.gradle.plugins.cmake.params.entries.CMakeCacheEntriesWithValueAutoGenerated

interface AppleEntriesProps : PlatformEntriesProps {
    val macosxBundle: String?
    val macosxRpath: String?
    val osxArchitectures: String?
    val osxDeploymentTarget: String?
    val osxSysroot: String?
}

interface AppleEntries : AppleEntriesProps, PlatformEntries

interface ModifiableAppleEntries : AppleEntries, ModifiablePlatformEntries {
    override var macosxBundle: String?
    override var macosxRpath: String?
    override var osxArchitectures: String?
    override var osxDeploymentTarget: String?
    override var osxSysroot: String?
}

interface AppleEntriesAutoGen : AppleEntries, CMakeCacheEntriesWithValueAutoGenerated {
    override val propertyNameToKey: Map<String, String>
        get() = mapOf(
            "macosxBundle" to "CMAKE_MACOSX_BUNDLE",
            "macosxRpath" to "CMAKE_MACOSX_RPATH",
            "osxArchitectures" to "CMAKE_OSX_ARCHITECTURES",
            "osxDeploymentTarget" to "CMAKE_OSX_DEPLOYMENT_TARGET",
            "osxSysroot" to "CMAKE_OSX_SYSROOT"
        )
}

/**
 * This abstract class represents the Apple specific entries for the CMake build system.
 * It extends the AbstractPlatformEntries class.
 * Specific Apple entries should be added in the classes that extend this class.
 */
abstract class AppleEntriesImpl : AbstractPlatformEntries(), AppleEntriesAutoGen {
    override val macosxBundle: String? = null
    override val macosxRpath: String? = null
    override val osxArchitectures: String? = null
    override val osxDeploymentTarget: String? = null
    override val osxSysroot: String? = null

    override val propertyNameToKey: Map<String, String>
        get() = super<AbstractPlatformEntries>.propertyNameToKey + super<AppleEntriesAutoGen>.propertyNameToKey
}

abstract class ModifiableAppleEntriesImpl : ModifiablePlatformEntriesImpl(), ModifiableAppleEntries,
    AppleEntriesAutoGen {

    override val propertyNameToKey: Map<String, String>
        get() = super<ModifiablePlatformEntriesImpl>.propertyNameToKey +
                super<AppleEntriesAutoGen>.propertyNameToKey

    override var macosxBundle: String? by recorder.observed(null)
    override var macosxRpath: String? by recorder.observed(null)
    override var osxArchitectures: String? by recorder.observed(null)
    override var osxDeploymentTarget: String? by recorder.observed(null)
    override var osxSysroot: String? by recorder.observed(null)
}